/* automatically generated by rust-bindgen */

pub type Enum_H5C_cache_incr_mode = ::libc::c_uint;
pub const H5C_incr__off: ::libc::c_uint = 0;
pub const H5C_incr__threshold: ::libc::c_uint = 1;
pub type Enum_H5C_cache_flash_incr_mode = ::libc::c_uint;
pub const H5C_flash_incr__off: ::libc::c_uint = 0;
pub const H5C_flash_incr__add_space: ::libc::c_uint = 1;
pub type Enum_H5C_cache_decr_mode = ::libc::c_uint;
pub const H5C_decr__off: ::libc::c_uint = 0;
pub const H5C_decr__threshold: ::libc::c_uint = 1;
pub const H5C_decr__age_out: ::libc::c_uint = 2;
pub const H5C_decr__age_out_with_threshold: ::libc::c_uint = 3;
