/* automatically generated by rust-bindgen */


extern "C" {
    pub fn H5FD_log_init() -> hid_t;
    pub fn H5FD_log_term() -> ();
    pub fn H5Pset_fapl_log(fapl_id: hid_t, logfile: *const ::libc::c_char,
                           flags: ::libc::c_ulonglong, buf_size: size_t)
     -> herr_t;
}
