/* automatically generated by rust-bindgen */

#[link(name = "hdf5")]
extern "C" {
    pub fn H5FD_multi_init() -> hid_t;
    pub fn H5FD_multi_term() -> ();
    pub fn H5Pset_fapl_multi(fapl_id: hid_t, memb_map: *const H5FD_mem_t,
                             memb_fapl: *const hid_t,
                             memb_name: *const *const ::libc::c_char,
                             memb_addr: *const haddr_t, relax: hbool_t)
     -> herr_t;
    pub fn H5Pget_fapl_multi(fapl_id: hid_t, memb_map: *mut H5FD_mem_t,
                             memb_fapl: *mut hid_t,
                             memb_name: *mut *mut ::libc::c_char,
                             memb_addr: *mut haddr_t, relax: *mut hbool_t)
     -> herr_t;
    pub fn H5Pset_fapl_split(fapl: hid_t, meta_ext: *const ::libc::c_char,
                             meta_plist_id: hid_t,
                             raw_ext: *const ::libc::c_char,
                             raw_plist_id: hid_t) -> herr_t;
}
