/* automatically generated by rust-bindgen */


extern "C" {
    pub fn H5FD_family_init() -> hid_t;
    pub fn H5FD_family_term() -> ();
    pub fn H5Pset_fapl_family(fapl_id: hid_t, memb_size: hsize_t,
                              memb_fapl_id: hid_t) -> herr_t;
    pub fn H5Pget_fapl_family(fapl_id: hid_t, memb_size: *mut hsize_t,
                              memb_fapl_id: *mut hid_t) -> herr_t;
}
