/* automatically generated by rust-bindgen */

pub type Enum_H5FD_mpio_xfer_t = ::libc::c_uint;
pub const H5FD_MPIO_INDEPENDENT: ::libc::c_uint = 0;
pub const H5FD_MPIO_COLLECTIVE: ::libc::c_uint = 1;
pub type H5FD_mpio_xfer_t = Enum_H5FD_mpio_xfer_t;
pub type Enum_H5FD_mpio_chunk_opt_t = ::libc::c_uint;
pub const H5FD_MPIO_CHUNK_DEFAULT: ::libc::c_uint = 0;
pub const H5FD_MPIO_CHUNK_ONE_IO: ::libc::c_uint = 1;
pub const H5FD_MPIO_CHUNK_MULTI_IO: ::libc::c_uint = 2;
pub type H5FD_mpio_chunk_opt_t = Enum_H5FD_mpio_chunk_opt_t;
pub type Enum_H5FD_mpio_collective_opt_t = ::libc::c_uint;
pub const H5FD_MPIO_COLLECTIVE_IO: ::libc::c_uint = 0;
pub const H5FD_MPIO_INDIVIDUAL_IO: ::libc::c_uint = 1;
pub type H5FD_mpio_collective_opt_t = Enum_H5FD_mpio_collective_opt_t;
