/* automatically generated by rust-bindgen */

pub type Enum_H5G_storage_type_t = ::libc::c_int;
pub const H5G_STORAGE_TYPE_UNKNOWN: ::libc::c_int = -1;
pub const H5G_STORAGE_TYPE_SYMBOL_TABLE: ::libc::c_int = 0;
pub const H5G_STORAGE_TYPE_COMPACT: ::libc::c_int = 1;
pub const H5G_STORAGE_TYPE_DENSE: ::libc::c_int = 2;
pub type H5G_storage_type_t = Enum_H5G_storage_type_t;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_H5G_info_t {
    pub storage_type: H5G_storage_type_t,
    pub nlinks: hsize_t,
    pub max_corder: int64_t,
    pub mounted: hbool_t,
}
impl ::std::clone::Clone for Struct_H5G_info_t {
    fn clone(&self) -> Struct_H5G_info_t { *self }
}
impl ::std::default::Default for Struct_H5G_info_t {
    fn default() -> Struct_H5G_info_t { unsafe { ::std::mem::zeroed() } }
}
pub type H5G_info_t = Struct_H5G_info_t;
pub type Enum_H5G_obj_t = ::libc::c_int;
pub const H5G_UNKNOWN: ::libc::c_int = -1;
pub const H5G_GROUP: ::libc::c_int = 0;
pub const H5G_DATASET: ::libc::c_int = 1;
pub const H5G_TYPE: ::libc::c_int = 2;
pub const H5G_LINK: ::libc::c_int = 3;
pub const H5G_UDLINK: ::libc::c_int = 4;
pub const H5G_RESERVED_5: ::libc::c_int = 5;
pub const H5G_RESERVED_6: ::libc::c_int = 6;
pub const H5G_RESERVED_7: ::libc::c_int = 7;
pub type H5G_obj_t = Enum_H5G_obj_t;
pub type H5G_iterate_t =
    ::std::option::Option<extern "C" fn(group: hid_t,
                                        name: *const ::libc::c_char,
                                        op_data: *mut ::libc::c_void)
                              -> herr_t>;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_H5G_stat_t {
    pub fileno: [::libc::c_ulong; 2usize],
    pub objno: [::libc::c_ulong; 2usize],
    pub nlink: ::libc::c_uint,
    pub _type: H5G_obj_t,
    pub mtime: time_t,
    pub linklen: size_t,
    pub ohdr: H5O_stat_t,
}
impl ::std::clone::Clone for Struct_H5G_stat_t {
    fn clone(&self) -> Struct_H5G_stat_t { *self }
}
impl ::std::default::Default for Struct_H5G_stat_t {
    fn default() -> Struct_H5G_stat_t { unsafe { ::std::mem::zeroed() } }
}
pub type H5G_stat_t = Struct_H5G_stat_t;

extern "C" {
    pub fn H5Gcreate2(loc_id: hid_t, name: *const ::libc::c_char,
                      lcpl_id: hid_t, gcpl_id: hid_t, gapl_id: hid_t)
     -> hid_t;
    pub fn H5Gcreate_anon(loc_id: hid_t, gcpl_id: hid_t, gapl_id: hid_t)
     -> hid_t;
    pub fn H5Gopen2(loc_id: hid_t, name: *const ::libc::c_char,
                    gapl_id: hid_t) -> hid_t;
    pub fn H5Gget_create_plist(group_id: hid_t) -> hid_t;
    pub fn H5Gget_info(loc_id: hid_t, ginfo: *mut H5G_info_t) -> herr_t;
    pub fn H5Gget_info_by_name(loc_id: hid_t, name: *const ::libc::c_char,
                               ginfo: *mut H5G_info_t, lapl_id: hid_t)
     -> herr_t;
    pub fn H5Gget_info_by_idx(loc_id: hid_t,
                              group_name: *const ::libc::c_char,
                              idx_type: H5_index_t, order: H5_iter_order_t,
                              n: hsize_t, ginfo: *mut H5G_info_t,
                              lapl_id: hid_t) -> herr_t;
    pub fn H5Gclose(group_id: hid_t) -> herr_t;
    pub fn H5Gcreate1(loc_id: hid_t, name: *const ::libc::c_char,
                      size_hint: size_t) -> hid_t;
    pub fn H5Gopen1(loc_id: hid_t, name: *const ::libc::c_char) -> hid_t;
    pub fn H5Glink(cur_loc_id: hid_t, _type: H5L_type_t,
                   cur_name: *const ::libc::c_char,
                   new_name: *const ::libc::c_char) -> herr_t;
    pub fn H5Glink2(cur_loc_id: hid_t, cur_name: *const ::libc::c_char,
                    _type: H5L_type_t, new_loc_id: hid_t,
                    new_name: *const ::libc::c_char) -> herr_t;
    pub fn H5Gmove(src_loc_id: hid_t, src_name: *const ::libc::c_char,
                   dst_name: *const ::libc::c_char) -> herr_t;
    pub fn H5Gmove2(src_loc_id: hid_t, src_name: *const ::libc::c_char,
                    dst_loc_id: hid_t, dst_name: *const ::libc::c_char)
     -> herr_t;
    pub fn H5Gunlink(loc_id: hid_t, name: *const ::libc::c_char) -> herr_t;
    pub fn H5Gget_linkval(loc_id: hid_t, name: *const ::libc::c_char,
                          size: size_t, buf: *mut ::libc::c_char) -> herr_t;
    pub fn H5Gset_comment(loc_id: hid_t, name: *const ::libc::c_char,
                          comment: *const ::libc::c_char) -> herr_t;
    pub fn H5Gget_comment(loc_id: hid_t, name: *const ::libc::c_char,
                          bufsize: size_t, buf: *mut ::libc::c_char)
     -> ::libc::c_int;
    pub fn H5Giterate(loc_id: hid_t, name: *const ::libc::c_char,
                      idx: *mut ::libc::c_int, op: H5G_iterate_t,
                      op_data: *mut ::libc::c_void) -> herr_t;
    pub fn H5Gget_num_objs(loc_id: hid_t, num_objs: *mut hsize_t) -> herr_t;
    pub fn H5Gget_objinfo(loc_id: hid_t, name: *const ::libc::c_char,
                          follow_link: hbool_t, statbuf: *mut H5G_stat_t)
     -> herr_t;
    pub fn H5Gget_objname_by_idx(loc_id: hid_t, idx: hsize_t,
                                 name: *mut ::libc::c_char, size: size_t)
     -> ssize_t;
    pub fn H5Gget_objtype_by_idx(loc_id: hid_t, idx: hsize_t) -> H5G_obj_t;
}
