/* automatically generated by rust-bindgen */

pub type Enum_H5LT_lang_t = ::libc::c_int;
pub const H5LT_LANG_ERR: ::libc::c_int = -1;
pub const H5LT_DDL: ::libc::c_int = 0;
pub const H5LT_C: ::libc::c_int = 1;
pub const H5LT_FORTRAN: ::libc::c_int = 2;
pub const H5LT_NO_LANG: ::libc::c_int = 3;
pub type H5LT_lang_t = Enum_H5LT_lang_t;

extern "C" {
    pub fn H5LTmake_dataset(loc_id: hid_t, dset_name: *const ::libc::c_char,
                            rank: ::libc::c_int, dims: *const hsize_t,
                            type_id: hid_t, buffer: *const ::libc::c_void)
     -> herr_t;
    pub fn H5LTmake_dataset_char(loc_id: hid_t,
                                 dset_name: *const ::libc::c_char,
                                 rank: ::libc::c_int, dims: *const hsize_t,
                                 buffer: *const ::libc::c_char) -> herr_t;
    pub fn H5LTmake_dataset_short(loc_id: hid_t,
                                  dset_name: *const ::libc::c_char,
                                  rank: ::libc::c_int, dims: *const hsize_t,
                                  buffer: *const ::libc::c_short) -> herr_t;
    pub fn H5LTmake_dataset_int(loc_id: hid_t,
                                dset_name: *const ::libc::c_char,
                                rank: ::libc::c_int, dims: *const hsize_t,
                                buffer: *const ::libc::c_int) -> herr_t;
    pub fn H5LTmake_dataset_long(loc_id: hid_t,
                                 dset_name: *const ::libc::c_char,
                                 rank: ::libc::c_int, dims: *const hsize_t,
                                 buffer: *const ::libc::c_long) -> herr_t;
    pub fn H5LTmake_dataset_float(loc_id: hid_t,
                                  dset_name: *const ::libc::c_char,
                                  rank: ::libc::c_int, dims: *const hsize_t,
                                  buffer: *const ::libc::c_float) -> herr_t;
    pub fn H5LTmake_dataset_double(loc_id: hid_t,
                                   dset_name: *const ::libc::c_char,
                                   rank: ::libc::c_int, dims: *const hsize_t,
                                   buffer: *const ::libc::c_double) -> herr_t;
    pub fn H5LTmake_dataset_string(loc_id: hid_t,
                                   dset_name: *const ::libc::c_char,
                                   buf: *const ::libc::c_char) -> herr_t;
    pub fn H5LTread_dataset(loc_id: hid_t, dset_name: *const ::libc::c_char,
                            type_id: hid_t, buffer: *mut ::libc::c_void)
     -> herr_t;
    pub fn H5LTread_dataset_char(loc_id: hid_t,
                                 dset_name: *const ::libc::c_char,
                                 buffer: *mut ::libc::c_char) -> herr_t;
    pub fn H5LTread_dataset_short(loc_id: hid_t,
                                  dset_name: *const ::libc::c_char,
                                  buffer: *mut ::libc::c_short) -> herr_t;
    pub fn H5LTread_dataset_int(loc_id: hid_t,
                                dset_name: *const ::libc::c_char,
                                buffer: *mut ::libc::c_int) -> herr_t;
    pub fn H5LTread_dataset_long(loc_id: hid_t,
                                 dset_name: *const ::libc::c_char,
                                 buffer: *mut ::libc::c_long) -> herr_t;
    pub fn H5LTread_dataset_float(loc_id: hid_t,
                                  dset_name: *const ::libc::c_char,
                                  buffer: *mut ::libc::c_float) -> herr_t;
    pub fn H5LTread_dataset_double(loc_id: hid_t,
                                   dset_name: *const ::libc::c_char,
                                   buffer: *mut ::libc::c_double) -> herr_t;
    pub fn H5LTread_dataset_string(loc_id: hid_t,
                                   dset_name: *const ::libc::c_char,
                                   buf: *mut ::libc::c_char) -> herr_t;
    pub fn H5LTget_dataset_ndims(loc_id: hid_t,
                                 dset_name: *const ::libc::c_char,
                                 rank: *mut ::libc::c_int) -> herr_t;
    pub fn H5LTget_dataset_info(loc_id: hid_t,
                                dset_name: *const ::libc::c_char,
                                dims: *mut hsize_t,
                                type_class: *mut H5T_class_t,
                                type_size: *mut size_t) -> herr_t;
    pub fn H5LTfind_dataset(loc_id: hid_t, name: *const ::libc::c_char)
     -> herr_t;
    pub fn H5LTset_attribute_string(loc_id: hid_t,
                                    obj_name: *const ::libc::c_char,
                                    attr_name: *const ::libc::c_char,
                                    attr_data: *const ::libc::c_char)
     -> herr_t;
    pub fn H5LTset_attribute_char(loc_id: hid_t,
                                  obj_name: *const ::libc::c_char,
                                  attr_name: *const ::libc::c_char,
                                  buffer: *const ::libc::c_char, size: size_t)
     -> herr_t;
    pub fn H5LTset_attribute_uchar(loc_id: hid_t,
                                   obj_name: *const ::libc::c_char,
                                   attr_name: *const ::libc::c_char,
                                   buffer: *const ::libc::c_uchar,
                                   size: size_t) -> herr_t;
    pub fn H5LTset_attribute_short(loc_id: hid_t,
                                   obj_name: *const ::libc::c_char,
                                   attr_name: *const ::libc::c_char,
                                   buffer: *const ::libc::c_short,
                                   size: size_t) -> herr_t;
    pub fn H5LTset_attribute_ushort(loc_id: hid_t,
                                    obj_name: *const ::libc::c_char,
                                    attr_name: *const ::libc::c_char,
                                    buffer: *const ::libc::c_ushort,
                                    size: size_t) -> herr_t;
    pub fn H5LTset_attribute_int(loc_id: hid_t,
                                 obj_name: *const ::libc::c_char,
                                 attr_name: *const ::libc::c_char,
                                 buffer: *const ::libc::c_int, size: size_t)
     -> herr_t;
    pub fn H5LTset_attribute_uint(loc_id: hid_t,
                                  obj_name: *const ::libc::c_char,
                                  attr_name: *const ::libc::c_char,
                                  buffer: *const ::libc::c_uint, size: size_t)
     -> herr_t;
    pub fn H5LTset_attribute_long(loc_id: hid_t,
                                  obj_name: *const ::libc::c_char,
                                  attr_name: *const ::libc::c_char,
                                  buffer: *const ::libc::c_long, size: size_t)
     -> herr_t;
    pub fn H5LTset_attribute_long_long(loc_id: hid_t,
                                       obj_name: *const ::libc::c_char,
                                       attr_name: *const ::libc::c_char,
                                       buffer: *const ::libc::c_longlong,
                                       size: size_t) -> herr_t;
    pub fn H5LTset_attribute_ulong(loc_id: hid_t,
                                   obj_name: *const ::libc::c_char,
                                   attr_name: *const ::libc::c_char,
                                   buffer: *const ::libc::c_ulong,
                                   size: size_t) -> herr_t;
    pub fn H5LTset_attribute_float(loc_id: hid_t,
                                   obj_name: *const ::libc::c_char,
                                   attr_name: *const ::libc::c_char,
                                   buffer: *const ::libc::c_float,
                                   size: size_t) -> herr_t;
    pub fn H5LTset_attribute_double(loc_id: hid_t,
                                    obj_name: *const ::libc::c_char,
                                    attr_name: *const ::libc::c_char,
                                    buffer: *const ::libc::c_double,
                                    size: size_t) -> herr_t;
    pub fn H5LTget_attribute(loc_id: hid_t, obj_name: *const ::libc::c_char,
                             attr_name: *const ::libc::c_char,
                             mem_type_id: hid_t, data: *mut ::libc::c_void)
     -> herr_t;
    pub fn H5LTget_attribute_string(loc_id: hid_t,
                                    obj_name: *const ::libc::c_char,
                                    attr_name: *const ::libc::c_char,
                                    data: *mut ::libc::c_char) -> herr_t;
    pub fn H5LTget_attribute_char(loc_id: hid_t,
                                  obj_name: *const ::libc::c_char,
                                  attr_name: *const ::libc::c_char,
                                  data: *mut ::libc::c_char) -> herr_t;
    pub fn H5LTget_attribute_uchar(loc_id: hid_t,
                                   obj_name: *const ::libc::c_char,
                                   attr_name: *const ::libc::c_char,
                                   data: *mut ::libc::c_uchar) -> herr_t;
    pub fn H5LTget_attribute_short(loc_id: hid_t,
                                   obj_name: *const ::libc::c_char,
                                   attr_name: *const ::libc::c_char,
                                   data: *mut ::libc::c_short) -> herr_t;
    pub fn H5LTget_attribute_ushort(loc_id: hid_t,
                                    obj_name: *const ::libc::c_char,
                                    attr_name: *const ::libc::c_char,
                                    data: *mut ::libc::c_ushort) -> herr_t;
    pub fn H5LTget_attribute_int(loc_id: hid_t,
                                 obj_name: *const ::libc::c_char,
                                 attr_name: *const ::libc::c_char,
                                 data: *mut ::libc::c_int) -> herr_t;
    pub fn H5LTget_attribute_uint(loc_id: hid_t,
                                  obj_name: *const ::libc::c_char,
                                  attr_name: *const ::libc::c_char,
                                  data: *mut ::libc::c_uint) -> herr_t;
    pub fn H5LTget_attribute_long(loc_id: hid_t,
                                  obj_name: *const ::libc::c_char,
                                  attr_name: *const ::libc::c_char,
                                  data: *mut ::libc::c_long) -> herr_t;
    pub fn H5LTget_attribute_long_long(loc_id: hid_t,
                                       obj_name: *const ::libc::c_char,
                                       attr_name: *const ::libc::c_char,
                                       data: *mut ::libc::c_longlong)
     -> herr_t;
    pub fn H5LTget_attribute_ulong(loc_id: hid_t,
                                   obj_name: *const ::libc::c_char,
                                   attr_name: *const ::libc::c_char,
                                   data: *mut ::libc::c_ulong) -> herr_t;
    pub fn H5LTget_attribute_float(loc_id: hid_t,
                                   obj_name: *const ::libc::c_char,
                                   attr_name: *const ::libc::c_char,
                                   data: *mut ::libc::c_float) -> herr_t;
    pub fn H5LTget_attribute_double(loc_id: hid_t,
                                    obj_name: *const ::libc::c_char,
                                    attr_name: *const ::libc::c_char,
                                    data: *mut ::libc::c_double) -> herr_t;
    pub fn H5LTget_attribute_ndims(loc_id: hid_t,
                                   obj_name: *const ::libc::c_char,
                                   attr_name: *const ::libc::c_char,
                                   rank: *mut ::libc::c_int) -> herr_t;
    pub fn H5LTget_attribute_info(loc_id: hid_t,
                                  obj_name: *const ::libc::c_char,
                                  attr_name: *const ::libc::c_char,
                                  dims: *mut hsize_t,
                                  type_class: *mut H5T_class_t,
                                  type_size: *mut size_t) -> herr_t;
    pub fn H5LTtext_to_dtype(text: *const ::libc::c_char,
                             lang_type: H5LT_lang_t) -> hid_t;
    pub fn H5LTdtype_to_text(dtype: hid_t, str: *mut ::libc::c_char,
                             lang_type: H5LT_lang_t, len: *mut size_t)
     -> herr_t;
    pub fn H5LTfind_attribute(loc_id: hid_t, name: *const ::libc::c_char)
     -> herr_t;
    pub fn H5LTpath_valid(loc_id: hid_t, path: *const ::libc::c_char,
                          check_object_valid: hbool_t) -> htri_t;
    pub fn H5LTopen_file_image(buf_ptr: *mut ::libc::c_void, buf_size: size_t,
                               flags: ::libc::c_uint) -> hid_t;
}
