/* automatically generated by rust-bindgen */

pub type H5MM_allocate_t =
    ::std::option::Option<extern "C" fn(size: size_t,
                                        alloc_info: *mut ::libc::c_void)
                              -> *mut ::libc::c_void>;
pub type H5MM_free_t =
    ::std::option::Option<extern "C" fn(mem: *mut ::libc::c_void,
                                        free_info: *mut ::libc::c_void)
                              -> ()>;
