/* automatically generated by rust-bindgen */

#[link(name = "hdf5_hl")]
extern "C" {
    pub fn H5PTcreate_fl(loc_id: hid_t, dset_name: *const ::libc::c_char,
                         dtype_id: hid_t, chunk_size: hsize_t,
                         compression: ::libc::c_int) -> hid_t;
    pub fn H5PTopen(loc_id: hid_t, dset_name: *const ::libc::c_char) -> hid_t;
    pub fn H5PTclose(table_id: hid_t) -> herr_t;
    pub fn H5PTappend(table_id: hid_t, nrecords: size_t,
                      data: *const ::libc::c_void) -> herr_t;
    pub fn H5PTget_next(table_id: hid_t, nrecords: size_t,
                        data: *mut ::libc::c_void) -> herr_t;
    pub fn H5PTread_packets(table_id: hid_t, start: hsize_t, nrecords: size_t,
                            data: *mut ::libc::c_void) -> herr_t;
    pub fn H5PTget_num_packets(table_id: hid_t, nrecords: *mut hsize_t)
     -> herr_t;
    pub fn H5PTis_valid(table_id: hid_t) -> herr_t;
    pub fn H5PTcreate_index(table_id: hid_t) -> herr_t;
    pub fn H5PTset_index(table_id: hid_t, pt_index: hsize_t) -> herr_t;
    pub fn H5PTget_index(table_id: hid_t, pt_index: *mut hsize_t) -> herr_t;
}
